# Mirror from rsync://mirror.funami.tech/arch-mact2 every 1 hour and upload to GitHub release in NoaHimesaka1873/arch-mact2-mirror repository
name: Mirror

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  Download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/repo
          key: arch-mact2-${{ commit.sha }}
          restore-keys: |
            arch-mact2-*

      - name: Download
        run: |
          rsync -avz --delete rsync://mirror.funami.tech/arch-mact2/ ${{ github.workspace }}/repo

      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ github.workspace }}/repo/os/x86_64
          gh release upload release ./* --clobber -R NoaHimesaka1873/arch-mact2-mirror

