# Mirror from https://mirror.funami.tech/arch-mact2/os/x86_64 every 1 hour and upload to GitHub release in NoaHimesaka1873/arch-mact2-mirror repository
name: Mirror

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  Download and upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download
        run: |
          wget -m -np -nH --cut-dirs=3 -e robots=off --reject "index.html*" -P ${{ github.workspace }}/repo https://mirror.funami.tech/arch-mact2/os/x86_64

      - name: Upload
        run: |
          cd ${{ github.workspace }}/repo
          gh release upload release ./* --clobber

