# Mirror from rsync://mirror.funami.tech/arch-mact2 every 1 hour and upload to GitHub release in NoaHimesaka1873/arch-mact2-mirror repository
name: Mirror

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  Download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/repo
          key: arch-mact2-${{ github.sha }} 
          fail-on-cache-miss: false

      - name: Download
        run: |
          rsync -avz --delete rsync://mirror.funami.tech/arch-mact2/ ${{ github.workspace }}/repo

      - name: Save Cache
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}/repo 
          key: arch-mact2-${{ github.sha }}

      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ github.workspace }}/repo/os/x86_64
          gh release upload release ./* --clobber -R NoaHimesaka1873/arch-mact2-mirror


